apiVersion: app/v1
kind: Deployment
metadata:
  name: mybackend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: willmaz/backend:latest
        ports:
        - containerPort: 8080