apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
      - name: loan-service
        image: willmaz/loan-service:latest
        ports:
        - containerPort: 3000