apiVersion: v1
kind: Service
metadata:
  name:  backend-service
spec:
  selector:
    app:  backend
  type:  LoadBalancer
  ports:
  - name:  backend-port
    port:  8080
    targetPort:  5000
---

apiVersion: v1
kind: Service
metadata:
  name:  loan-service-service
spec:
  selector:
    app:  loan-service
  type:  LoadBalancer
  ports:
  - name:  loan-service-port
    port:  8081
    targetPort:  3000